#!/bin/sh
# Copyright (c) 2023 Lajos Koszti

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


checkout_previous() {
  git checkout -
}

checkout_previous_n() {
  git checkout @{-$1}
}

list() {
  items_to_keep=${1:-10}
  git reflog | awk '/checkout: moving from/ { match($2, /{([0-9]+)}/, n); id=1+n[1];print id" "$6; }' | uniq -f 1 | sort -rn | tail -n $items_to_keep
}

help() {
  echo "Usage: git-branch-history {previous|p|previous-n|n|list|ls|help}"
}

while [ $# -gt 0 ];do
  case "$1" in
    previous|p)
      checkout_previous
      exit
      ;;
    previous-n|n)
      checkout_previous_n $2
      exit
      ;;
    list|ls)
      list $2
      exit
      ;;
    help|h)
      help
      exit
      ;;
    *)
      help >&2
      exit 1
  esac
  shift
done

# vi: ft=sh
